### ISSUE TITLE
Encounters API

### ISSUE THREAD

**Issue by samamorgan** [Lightmatter/welkin-health#16]
### `Encounters`
- GET
  - Encounter records/full records by Patient ID
  - Encounter records/full records by User ID
  - Encounter records/full records by Client ID from JWT token (do we need this? Unsure of how this is useful. Some test queries might be revealing)

### `Encounter`
- GET
  - Encounter record/full record by Patient ID and Encounter ID
- POST
   - Create an encounter for Patient
- PATCH
  - Update Encounter for Patient by ID
- DELETE
  - Delete encounter record for Patient by Encounter ID

Bonuses:
- `Comments`
- `AssessmentLinks`
- `DispositionRecord`
- `DispositionFormation`
- `Templates`

## Implementation ideas
Nested resources? Ex:
```python
patient = welkin.Patient(id="{id}").get()

encounters = patient.Encounters().get()
encounter_comments = patient_encounters[0].Comments().get()

encounter = patient.Encounter(id="{id}").get()
```

**Comment by edcohen08** [comment]
Closed by #19 , does not include any of the bonuses
