### ISSUE TITLE
Assessments & Assessment Records

### ISSUE THREAD

**Issue by edcohen08** [Lightmatter/welkin-health#24]
Specifically the nested Assessment Records under patients and the nested Encounter Assessments under Encounters 

### `AssessmentRecords`
- GET
  - Assessment records by patient id
 
### `AssessmentRecord`
- GET
  - Assessment record by patient id and assessment record id 
- POST
   - Create an assessment record by patient id, assessment name in body
- PUT
  - Update status of an assessment record by patient id, assessment record id
- PUT
  - Update answers on an assessment record by patient id, assessment record id
- DELETE
  - Delete encounter record for Patient by Encounter ID

### `Assessments`
- GET
  - All assessments on an encounter by encounter id

### `Assessment`
- GET
  - Encounter assessment by patient id, encounter id and assessment id
- POST
   - Create a link between an encounter and an assessment by patient id and encounter id. Assessment name and assessment record id in body
- PATCH
  - Update link between an encounter and an assessment by patient id, encounter id and assessment id. new assessment record in body.
- DELETE
  - Delete link between an encounter and an assessment by patient id, encounter id and assessment id

**Comment by samamorgan** [comment]
Closed by #27
