### ISSUE TITLE
Retry time is excessive

### ISSUE THREAD

**Issue by alonzopt** [Lightmatter/welkin-health#34]
While it is configurable when initializing the client, current defaults means if the wrapper receives certain status codes (`429, 500, 502, 503, 504`) the wrapper will sleep for 1,2,4,8 minute(s) between requests before giving up and throwing an error, meaning a failing request can sit for 15 minutes before being raised.

The formula to determine the number of seconds to sleep between retries is
```
{backoff factor} * (2 ** ({number of attempted retries} - 1))
```
with the current defaults in the client being
```
        total=5,
        backoff_factor=30
```
5 retries seems reasonable.

urllib3's default `backoff_factor` is `0` (i.e. off) and is a float so can be set to <1 second.
At `backoff_factor=1` it will be 30 seconds before an exception is raised.
I think the default for `backoff_factor`, if not `0` to match urllib3, should not exceed `1`.

**Comment by samamorgan** [comment]
Sounds reasonable to me. Want to make a quick PR for this?
