### ISSUE TITLE
Implement Welkin Formation Fetching

### ISSUE THREAD

**Issue by samamorgan** [Lightmatter/welkin-health#37]
We're currently only interfacing with Instance and Admin data. Formation data is incredibly helpful for understanding how the data is structured on Welkin.

For instance, our current CDT implementation is _actually_ for CDT records. CDTs are the definition of the data, CDT records are the rows on that data table.

To fetch CDT records, the URL is:

`https://api.live.welkincloud.io/{tenant}/{instance/}formations/{current *OR* version number}/cdts`

Note: Most of the formation endpoints are completely undocumented. I assume that all formation endpoints are allowed GET for API clients.

**Comment by edcohen08** [comment]
Closed by #38
