### ISSUE TITLE
New release possible?

### ISSUE THREAD

**Issue by edwardmsmith** [Lightmatter/welkin-health#61]
Hi all -

Is it possible to get a new release cut and pushed to package managers with the new Work Hours feature?  I'm happy to take on any of the work, if possible.

thanks!

**Comment by edcohen08** [comment]
@edwardmsmith just made a new release [here](https://github.com/Lightmatter/welkin-health/releases/tag/v0.0.8)

**Comment by edcohen08** [comment]
Update: we're working out some issues with the release, will keep you posted

**Comment by edcohen08** [comment]
It's an issue with actually releasing though and not the package so if it is timely please feel free to install the package via the github link rather than pypi

**Comment by edcohen08** [comment]
Release [v0.0.8](https://github.com/Lightmatter/welkin-health/releases/tag/v0.0.8) is live now
